# -*- coding: utf-8 -*-
"""
集中文案表(strings table):把 UI 界面文案从调用点抽出来,集中成一份可通读、可批量改「用户话」的清单。

设计:
    - 这是【纯数据】模块,只放 STRINGS 字典,不放逻辑、不 import i18n。
    - i18n.t() 已升级为:遇到字符串 ID → 查本表;遇到元组/旧两参 → 原样。
    - 因此调用点可以三种写:
        t("中文", "英文")         旧式两参(仍可用,不用改)
        t(("中文", "英文"))       元组直传
        t("VER_ID")               新式 ID(查本表)

约定:
    - ID = 语义化命名 (大写下划线, 前缀可按页面: VERSION_HOME_ / RESOURCE_ / SETTINGS_ ...)。
    - (中文, 英文) 原样搬运自调用点:先只加 ID、精确复制,【不在此步做内容改写】。
    - 内容里的 emoji 是"当时改动较大、暂时保留"的,待「文案说人话」批次再统一清除。
"""
STRINGS = {
    "AI_ASSISTANT": ("AI 助手", "AI Assistant"),
    "AMCL_LAUNCHER": ("AMCL 启动器", "AMCL Launcher"),
    "ANY_LOADER": ("无(全部加载器)", "Any loader"),
    "ANY_VERSION": ("无(全部版本)", "Any version"),
    "AUTO_CONFIG_FAILED_ERR": ("自动配置失败:需联网,首次使用请点击下载;或手动按教程装。", "Auto-config failed: {err}"),
    "AUTO_SETUP_NEEDS_INTERNET_CLICK_TO_DOWNLOAD_INSTALL_FIRST_OR_INSTALL_MANUALLY": ("自动设置需要联网:第一次用请先点下载/安装(或按教程手动装)。", "Auto-setup needs internet: click to download/install first (or install manually)."),
    "AUTO_SETUP_NOT_READY_BACKEND_UNAVAILABLE_OPEN_THE_WEBSITE_TO_DOWNLOAD_OR_FOLLOW_THE_TUTORIAL": ("自动设置用不了:需要联网先下载才能用。先「打开官网」下载安装,或按教程手动装。", "Auto-setup isn't ready: it needs to be downloaded first. Open the website to install, or follow the manual tutorial."),
    "BACK": ("← 上一步", "← Back"),
    "BACKEND_NOT_READY_OPEN_THE_WEBSITE_OR_INSTALL_MANUALLY": ("自动设置还不可用:先「打开官网」下载,或按教程手动装。", "Auto-setup isn't available yet: open the website to install, or follow the manual tutorial."),
    "BASICS": ("基本概念", "Basics"),
    "BEGINNER_TUTORIAL": ("新手教程", "Beginner Tutorial"),
    "BRIDGE_MOD": ("bridge-mod(游戏内指令口 / 数据导出)", "bridge-mod"),
    "BROWSE_RESOURCES": ("像逛商场一样挑资源:", "Browse resources:"),
    "CACHED_TRANSLATION": ("已缓存翻译", "Cached translation"),
    "CHECK_FOR_UPDATES": ("检查更新…", "Check for Updates…"),
    "CHECK_FOR_UPDATES_ALT": ("检查更新", "Check for Updates"),
    "CLEAR_ALL_TAGS": ("清除所有标签", "Clear all tags"),
    "CLOSE": ("关闭", "Close"),
    "CREATE_INSTANCE": ("创建实例", "Instances"),
    "DATAPACKS": ("数据包", "Datapacks"),
    "DOWNLOAD": ("下载", "Download"),
    "DOWNLOADING_0": ("下载中 0%…", "Downloading 0%…"),
    "DOWNLOADING_LOCAL_MODEL_MIRROR_FIRST": ("正在后台下载本地模型(镜像优先)…", "Downloading local model (mirror first)…"),
    "DOWNLOAD_INSTALL_GENERATE_ROOM": ("下载/安装并生成房间", "Download/install & generate room"),
    "DOWNLOAD_LOCAL_MODEL": ("下载本地模型", "Download local model"),
    "DOWNLOAD_UPDATE": ("下载并更新", "Download & Update"),
    "EASYTIER_READY_GENERATE_A_ROOM": ("EasyTier 已就绪,可一键生成房间。", "EasyTier ready — generate a room."),
    "FAVORITES": ("收藏夹", "Favorites"),
    "FULL_MORE_TIPS_GUIDES": ("全面(显示更多提示与科普)", "Full (more tips & guides)"),
    "FULL_SHOWS_RESOURCE_GUIDE_DETAILED_HINTS_SUMMARY_HIDES_THEM_CONCISE": ("全面:首页多给你讲资源结构,提示更详细;摘要:去掉科普,只留必要的。", "Full: home shows resource guide & more detail; Summary: hides the extra, keeps it simple."),
    "GAME": ("游戏", "Game"),
    "UI": ("界面", "UI"),
    "SYSTEM": ("系统", "System"),
    "GAME_VERSION_CLICK_A_MAJOR_TO_AUTO_PICK": ("选游戏版本(点一个系列,自动帮你挑好)", "Game version (click a series to auto-pick)"),
    "GENERATE_ROOM_SHARE": ("一键生成房间并分享", "Generate room & share"),
    "HOME": ("首页", "Home"),
    "INSTALL_TO": ("安装到", "Install to"),
    "INSTANCES": ("实例", "Instances"),
    "INSTANCE_DETAILS": ("实例详情", "Instance Details"),
    "INSTANCE_SETTINGS": ("实例设置", "Instance settings"),
    "LATEST_RELEASE_LATEST_SNAPSHOT": ("最新正式版: -- | 最新快照版: --", "Latest release: -- | Latest snapshot: --"),
    "LAUNCHER_PLUGINS": ("启动器插件", "Plugins"),
    "LOADER": ("加载器", "Loader"),
    "LOADER_EXPLAIN": ("加载器 = 让 Mod 能跑起来的「底座」。Fabric / Forge / NeoForge 是三种最常用的;"
                       "想装 Mod 就选一个,只玩原版就选「无」。", "Loader = the base that lets mods run. "
                       "Fabric / Forge / NeoForge are the common ones; pick one to add mods, "
                       "or 'None' for vanilla."),
    "LOADING": ("加载中...", "Loading..."),
    "LOCAL_MODEL_DOWNLOADED_READY": ("本地模型已下载,可直接使用", "Local model downloaded, ready"),
    "LOGIN_INFO_UPDATED": ("登录信息已更新", "Login info updated"),
    "MACHINE_TRANSLATION_LOW_CONFIDENCE_SEE_ORIGINAL": ("这是机器翻译,可信度较低,请以英文原文为准。", "This is a low-confidence machine translation; refer to the English original."),
    "MACHINE_TRANSLATION_SEE_ORIGINAL_FOR_ACCURACY": ("这是机器翻译,可能不准确,请以英文原文为准。", "This is a machine translation and may be off; refer to the English original."),
    "MANUAL_DOWNLOAD": ("手动下载", "Manual download"),
    "MC_RESOURCE_TYPES_READ_BEFORE_PICKING": ("了解一下 MC 资源类型(自己挑资源前先看一眼):", "MC resource types (read before picking):"),
    "MIRROR": ("镜像源", "Mirror"),
    "MODPACKS": ("整合包", "Modpacks"),
    "MODPACK_MODS_CONFIG_OPTIONAL_SAVES_IN_ONE_PICK_A_VERSION_AND_DOWNLOAD_IT_AUTO_DOWNLOADS_THE_MRPACK_AND_IMPORTS_AS_A_NEW_INSTANCE": ("整合包 = 把一堆 Mod 和配置打包好。选好版本点「下载」,它会自动下载并装成一个新游戏,不用先挑装到哪。", "A modpack = a bundle of mods & configs. Pick a version and Download: it auto-installs as a new game, no need to pick a target first."),
    "MODS": ("Mod", "Mods"),
    "MOD_VERSION": ("mod版本", "Mod version"),
    "MULTIPLAYER": ("联机", "Multiplayer"),
    "MY_INSTANCES": ("我的实例", "My Instances"),
    "NEEDS_GENUINE_MS_ACCOUNT": ("这个方案需要正版 Minecraft 账号(微软);离线或非正版账号用不了。", "This option needs a genuine Microsoft Minecraft account; offline/pirated accounts won't work."),
    "NO": ("否", "No"),
    "NONE_PICK_FOLDER": ("无(手动选目录)", "None (pick folder)"),
    "NOT_DOWNLOADED_500MB_CLICK_TO_START": ("未下载(约 500MB,点按钮开始)", "Not downloaded (~500MB, click to start)"),
    "NO_RESULTS": ("(没有找到结果)", "(no results)"),
    "NO_TAGS": ("无标签", "No tags"),
    "NO_VERSIONS": ("(暂无可用版本)", "(no versions)"),
    "OPEN_OFFICIAL_TUTORIAL": ("查看官网/教程", "Open official tutorial"),
    "OPEN_PLUGIN_MANAGER": ("打开插件管理(设置→插件)", "Open plugin manager"),
    "OPEN_RELEASE_PAGE": ("查看发布页", "Open Release Page"),
    "OPEN_WEBSITE": ("打开官网", "Open website"),
    "PICK_A_GAME_VERSION_CLICK_A_MAJOR_TO_AUTO_PICK_ITS_RECOMMENDED_EXPAND_FOR_EXACT": ("选游戏版本:点一个系列(如 1.21),自动帮你挑最合适的具体版;展开能选得更精确。", "Pick a game version: click a series (e.g. 1.21) to auto-choose the best one for you; expand to pick it precisely."),
    "PICK_FOLDER": ("选择安装位置", "Pick folder"),
    "PLUGINS": ("插件", "Plugins"),
    "READY": ("已就绪", "Ready"),
    "READ_ONLY_GUIDE_WHAT_EACH_CONTROL_DOES": ("这里只讲解每个界面有什么、在哪、怎么用,不会改动你的任何设置。", "This only explains what each screen and control does; it doesn't change any of your settings."),
    "RECOMMEND": ("帮我推荐", "Recommend"),
    "RECOMMENDED": ("推荐方案:", "Recommended:"),
    "RELEASE_TO_INSTALL_AS_MODPACK": ("松手 → 尝试作为整合包安装", "Release to install as modpack"),
    "REPLAY_GUIDED_TUTORIAL": ("重播引导教程", "Replay guided tutorial"),
    "RESOURCEPACKS": ("资源包", "Resourcepacks"),
    "RESOURCES": ("下载新资源", "Resources"),
    "RESTART": ("重新开始", "Restart"),
    "RESTART_TO_APPLY": ("重启启动器生效", "Restart to apply"),
    "ROOM_CREATED_SEND_THE_ROOM_KEY_VIRTUAL_IP_TO_YOUR_FRIENDS": ("房间已生成;把房间钥匙与虚拟 IP 发给朋友即可。", "Room created — send the room key & virtual IP to your friends."),
    "ROOM_KEY_NAME_SECRET": ("房间钥匙(name + secret)", "Room key (name + secret)"),
    "SAVE_SETTINGS": ("保存设置", "Save settings"),
    "SEARCHING": ("搜索中...", "Searching..."),
    "SEARCH_FAILED_CHECK_NETWORK": ("搜索失败,请检查网络", "Search failed, check network"),
    "SELECT_AN_INSTANCE_ON_THE_RIGHT_FIRST": ("先在右边「版本」里选一个游戏。", "Select a game in the Versions list on the right first."),
    "SELECT_A_PROJECT_ON_THE_LEFT": ("← 在左侧选择一个项目", "← Select a project on the left"),
    "SETTINGS": ("设置", "Settings"),
    "SET_GAME_LOADER_MOD_VERSION": ("点开设置 游戏版本/加载器/mod版本", "Set game/loader/mod version"),
    "SHADERS": ("光影包", "Shaders"),
    "START_RECOMMEND_YES_NO": ("开始推荐(答是 / 否)", "Start recommend (yes/no)"),
    "SUMMARY_CONCISE": ("摘要(精简提示)", "Summary (concise)"),
    "TIP_THE_NEWEST_MC_VERSION_USUALLY_HAS_POOR_MOD_SUPPORT_PREFER_ACTIVE_VERSIONS_LIKE_1_21_1_1_20_1": ("提示:最新版本的游戏,Mod 往往还没跟上;建议用 Mod 多的版本,比如 1.21.1 或 1.20.1。", "Tip: the newest game version usually has fewer mods yet; prefer versions with lots of mods, like 1.21.1 or 1.20.1."),
    "TRANSLATING": ("正在翻译描述…", "Translating…"),
    "TRANSLATION_FAILED_SHOWING_ORIGINAL": ("翻译失败,已显示原文", "Translation failed, showing original"),
    "TUTORIALS": ("教程与资料", "Tutorials"),
    "UPDATE": ("更新", "Update"),
    "UPDATE_DOWNLOADED_THE_APP_WILL_RESTART": ("新版本已下载完成,马上自动退出并重启更新。", "The new version is downloaded; the app will restart to update."),
    "UPDATE_FAILED": ("更新失败", "Update Failed"),
    "VERSION_HOME_CHANGELOG": ("更新日志", "Changelog"),
    "VERSION_HOME_CHANGE_LOGIN": ("更改登录方式 ▾", "Change login ▾"),
    "VERSION_HOME_COMMUNITY": ("MC 动态", "Community"),
    "VERSION_HOME_COMMUNITY_FEED_PLANNED": ("MC 社区动态(规划中)\n\n未来这里会显示 Minecraft 社区动态、新闻等内容。当前为占位。", "MC community feed (planned)\n\nFuture home for community news. Placeholder."),
    "VERSION_HOME_CURRENT_SELECTION": ("当前选择", "Current selection"),
    "VERSION_HOME_EDIT_OFFLINE_NAME": ("修改离线昵称…", "Edit offline name…"),
    "VERSION_HOME_EDIT_OFFLINE_NAME_TITLE": ("修改离线昵称", "Edit offline name"),
    "VERSION_HOME_FETCHING_GH": ("正在从 GitHub 拉取…", "Fetching from GitHub…"),
    "VERSION_HOME_FETCH_FAILED": ("拉取失败,请检查网络后点「刷新」", "Fetch failed, check network and Refresh"),
    "VERSION_HOME_IMPORT_MODPACK": ("导入整合包", "Import Modpack"),
    "VERSION_HOME_INSTANCES": ("实例", "Instances"),
    "VERSION_HOME_LAUNCHER_LOG": ("启动器日志", "Launcher Log"),
    "VERSION_HOME_LAUNCH_GAME": ("启动游戏", "Launch Game"),
    "VERSION_HOME_MS_SIGNED_IN": ("微软正版 · 已登录", "Microsoft · signed in"),
    "VERSION_HOME_NO_INSTANCE_SELECTED": ("未选择实例", "No instance selected"),
    "VERSION_HOME_OFFLINE_IN_GAME_NAME": ("离线模式显示的游戏名:", "Offline in-game name:"),
    "VERSION_HOME_OFFLINE_NAME_EDITABLE": ("离线模式 · 昵称可改", "Offline · name editable"),
    "VERSION_HOME_ONE_CLICK": ("一键配置 ▾", "One-click ▾"),
    "VERSION_HOME_ONE_CLICK_BRIDGE": ("一键配置 bridge-mod(本地指令口,推荐)", "One-click bridge-mod (local command port, recommended)"),
    "VERSION_HOME_ONE_CLICK_RCON": ("一键配置 RCON(临时方案)", "One-click RCON (temporary)"),
    "VERSION_HOME_OPEN_LAUNCHER_SETTINGS": ("打开启动器设置…", "Open launcher settings…"),
    "VERSION_HOME_REFRESH": ("刷新", "Refresh"),
    "VERSION_HOME_SELECT_INSTANCE_FIRST": ("先选择实例", "Select an instance first"),
    "VERSION_HOME_SOURCE_URL": ("来源:github.com/erfanyo/Agent_Minecraft_Launcher/CHANGELOG.md", "Source: github.com/erfanyo/Agent_Minecraft_Launcher/CHANGELOG.md"),
    "VIEW_ON_MC_MOD": ("在 MC百科查看", "View on MC百科 (mcmod.cn)"),
    "VIEW_TUTORIAL": ("查看教程", "View tutorial"),
    "VIRTUAL_IP": ("虚拟 IP", "Virtual IP"),
    "YES": ("是", "Yes"),
}
