plugins {
    id 'net.minecraftforge.gradle' version '4.1.16'
}

group = 'com.agentmc'
version = '0.2.3'

repositories {
    maven { url = 'https://maven.minecraftforge.net' }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.16.5-36.2.39'
}

minecraft {
    mappings channel: 'official', version: '1.16.5'
}

sourceSets.main.java.srcDirs = ['src/main/java']
sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

compileJava.options.encoding = 'UTF-8'
jar {
    archiveBaseName = 'agentmc-bridge-forge-1.16.5'
    manifest { attributes('Implementation-Version': project.version) }
}
